### ISSUE TITLE
Not working in Laravel Valet

### ISSUE THREAD

**Issue by ursuleacv** [fastsitephp/starter-site#4]
PHP: 7.2
OS: Mac

Steps to reproduce 

1. install valet `https://laravel.com/docs/7.x/valet`
2. Install starter-site
    `composer create-project fastsitephp/starter-site fastsite`
3. Open the website at `http://fastsite.test`

Result:
redirect loop

`http://fastsite.test/public/en/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/public/`

Note: Working well in PHP built-in web server

**Comment by ConradSollitt** [comment]
Thanks @ursuleacv

I have a Mac so I'll test and report back soon. It might be later today but could be next week as well. The issue likely has to due with the main route at https://github.com/fastsitephp/starter-site/blob/master/app/app.php#L50 and my require changes to one of the two functions it calls `$app->rootUrl()` or `I18N::getUserDefaultLang()`.

I see that Laravel Valet uses nginx internally and when nginx is used on a live server the default route would run from `~/public/index.php` rather than `~/index.php` and a fallback resource would be specified so I'll just have to check how it's setup by default. The main route on the main route has some commented code related to fallback resource on specific setups. Regardless I hope to get it fixed so it works automatically.

I'll update this later.
Thanks

**Comment by ConradSollitt** [comment]
@ursuleacv 

Would you be able to help out with some testing with Laravel Valet? I don't want to install it just yet as I already have the default Mac Apache Setup on my machine and prefer to not disable it for Valet right now although I happy to test in more detail later.

If you can help test the first two things to test would be to see if the full URL paths work (one without `index.php` and one with):
~~~
http://fastsite.test/public/en/
http://fastsite.test/index.php/public/en/
~~~

Then in the file `~/app/app.php` at line 67 make the following changes:
~~~php
$app->get('/', function() use ($app) {
    header('Content-Type: text/plain');
    var_dump($_SERVER);
    exit();
~~~

Generally the variables of most interest would be:
~~~
SCRIPT_NAME
SCRIPT_FILENAME
REQUEST_URI
PATH_INFO
HTTP_HOST
~~~

I see that Valet has a number of drivers for various frameworks and CMS's at https://github.com/laravel/valet/tree/master/cli/drivers

I can see having to write a basic driver but ideally I would like to make it automated as possible, and at the very least need to see if the redirect bug can be solved without breaking other common environments. Currently the site will work on most Apache or IIS installations and at site root level or as a sub-directory level on servers that host a number of apps and for nginx it works with basic config.

**Comment by ConradSollitt** [comment]
@ursuleacv Would you be able to help out and share the variables that you see? It should be quick. If you are able to help out that would be much appreciated, however if not that is ok. I'll handle this in the future in that case but it won't be till late next week or likely later as I can't break my dev environment for this right now.

**Comment by ConradSollitt** [comment]
Updates will be published soon. Currently I'm testing on the main/master branch and once ready they will be published to composer. So far the only needed change on the starter site is in the root `index.php` page. 

https://github.com/fastsitephp/starter-site/blob/master/index.php

I'm also updating the main framework (which contains the live site if downloaded directly).

I'll post an update once everything is ready. After I finish getting it to work with Laravel Valet I'll need to revert my mac back to confirm it works with the default macOS Apache/php installation and also I'll test again on Windows with IIS Express.

This issue doesn't affect the Framework or production sites in any way, rather only the local development root `index.php` file that is not included on production servers/installs.

**Comment by ConradSollitt** [comment]
The latest release `1.3.2` now works with Laravel Valet using the steps described in the original issue.

Thanks @ursuleacv 
I've given you credit for finding and opening this issue in the change logs of this repository and the repository for the main framework:

https://github.com/fastsitephp/starter-site/blob/master/CHANGELOG.md

https://github.com/fastsitephp/fastsitephp/blob/master/CHANGELOG.md
